version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./certs:/certs:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'
    ports:
      - 9090:9090

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
    ports:
      - 8080:8080

  debug:
    image: alpine:latest
    command: sh -c "while true; do sleep 1000; done"
    volumes:
      - ./certs:/certs:ro
    tty: true